# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [array-enhanced, array-enhanced-mobx]
        mobx: [mobx@5, mobx@6]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: packages/${{ matrix.package }}/package-lock.json
    - run: npm ci
    - run: npm i ${{ matrix.mobx }} --save
    - run: npm run build
    - run: npm run test:no-watch
